### ISSUE TITLE
Nao foi possivel gerar o ZIP

### ISSUE THREAD

**Issue by renoleite** [michaelfp/pcf-endereco-control#3]
Ola Michael, parabens pelo trabalho com os controles PCF. Nao estou conseguindo gerar o ZIP para ambos seus PFC controls de CNPJ e Endereco, seria possivel subir o managed ZIP para o repositorio? Acredito ter alguma diferenca de versao de Framework ou algo assim aqui. Muito obrigado.

**Comment by michaelfp** [comment]
Olá. Qual o erro que esta acontecendo para você? Fiz aqui o build normalmente. Pode colar o erro que está ocorrendo?

Igualmente já fiz o update com as atualizações do PCF e subi um release com o zip já. Para baixar acesse a área de release do projeto.

Qualquer dúvida entre em contato.
