### ISSUE TITLE
Tentando subir a solução pelo make.powerapps

### ISSUE THREAD

**Issue by crisolegario** [michaelfp/pcf-endereco-control#6]
Olá
Michael

Parabéns pela solução!  Para mim que não sou desenvolvedor soluções como essa ajudam muito na implementação da ferramenta Dynamics.  Eu tentei importar a sua solução por make.powerapps porém tenho a seguinte mensagem:  "O arquivo compactado deve conter os seguintes arquivos na raiz: solution.xml, customizations.xml, e [Content_Types].xml". Porém em seus comentários vc orienta subir a solução por linha de comando certo? Vc possui um passo a passo para esta forma de instalação?  Ou ainda.. é possível importar a solução pelo make.powerapps?  Desde já agradeço a atenção

**Comment by michaelfp** [comment]
Olá. Tudo bem! Espero que esta solução posse te ajudar :).

Você consegue me dizer qual o zip que tentou subir. Há algumas semanas atrás eu coloquei o zip na página de release. 

https://github.com/michaelfp/pcf-endereco-control/releases/tag/1

Faça o donwload do cepControlSolution.zip que poderá importar diretamente no seu Power Apps/ Dynamics 365

**Comment by michaelfp** [comment]
Sem retorno
